#!/usr/bin/env python3
"""Generates the Home Assistant Overview dashboard config.

The Overview page is auto-generated by HA's default strategy until a config is
stored, at which point HA hands control over permanently. That stored config
lives only in HA's .storage and is invisible to this repo, so it is generated
here instead and applied with `ha/apply-dashboard.py`.

Rollback: delete the stored config (Overview -> pencil -> three dots -> "Delete
dashboard") and HA reverts to auto-generating it. Nothing here is destructive.

Entity IDs are hard-coded deliberately. A generated-from-discovery dashboard
reshuffles itself whenever a device drops off the network, which is precisely
when you least want the layout to move.
"""
import json
import os

def heading(text, icon=None):
    c = {"type": "heading", "heading": text, "heading_style": "title"}
    if icon:
        c["icon"] = icon
    return c

def tile(entity, **kw):
    c = {"type": "tile", "entity": entity}
    c.update(kw)
    return c

TOGGLE = {"features": [{"type": "toggle"}]}

# --- Alerts: only render when something actually needs attention. This is the
# difference between a dashboard and a list of entities.
alerts = {
    "type": "grid",
    "cards": [
        {
            "type": "conditional",
            "conditions": [{"condition": "state", "entity": "binary_sensor.zenwifi_bq16_pro_77f8_wan_status", "state": "off"}],
            "card": {"type": "markdown", "content": "## Internet is down\nThe router reports no WAN connectivity."},
        },
        {
            "type": "conditional",
            "conditions": [{"condition": "numeric_state", "entity": "sensor.mfc_j6960dw_black_toner_remaining", "below": 20}],
            "card": {"type": "markdown", "content": "## Printer: black ink low\n{{ states('sensor.mfc_j6960dw_black_toner_remaining') }}% remaining."},
        },
        {
            "type": "conditional",
            "conditions": [{"condition": "state", "entity": "sensor.backup_backup_manager_state", "state_not": "idle"}],
            "card": {"type": "entities", "title": "Backup running", "entities": ["sensor.backup_backup_manager_state"]},
        },
    ],
}

climate = {
    "type": "grid",
    "cards": [
        heading("Climate", "mdi:thermometer"),
        {"type": "thermostat", "entity": "climate.upstairs", "features": [{"type": "climate-hvac-modes"}]},
        tile("sensor.upstairs_current_temperature", name="Upstairs"),
        tile("sensor.upstairs_current_humidity", name="Humidity"),
        tile("sensor.juliettes_room_temperature", name="Juliette's room"),
        tile("sensor.lukes_room_temperature", name="Luke's room"),
        tile("binary_sensor.juliettes_room_occupancy", name="Juliette — occupied"),
        tile("binary_sensor.lukes_room_occupancy", name="Luke — occupied"),
    ],
}

lights = {
    "type": "grid",
    "cards": [
        heading("Lights & plugs", "mdi:lamp"),
        tile("switch.courtneys_lamp", name="Courtney's lamp", **TOGGLE),
        tile("switch.jeremys_lamp", name="Jeremy's lamp", **TOGGLE),
        tile("switch.my_swag", name="My Swag", **TOGGLE),
    ],
}

people = {
    "type": "grid",
    "cards": [
        heading("People", "mdi:account"),
        tile("person.jeremy_corbello", name="Jeremy"),
        tile("sensor.jeremys_iphone_battery_level", name="iPhone battery"),
        tile("sensor.jeremys_iphone_watch_battery_level", name="Watch battery"),
    ],
}

network = {
    "type": "grid",
    "cards": [
        heading("Network", "mdi:wan"),
        tile("binary_sensor.zenwifi_bq16_pro_77f8_wan_status", name="WAN"),
        tile("sensor.zenwifi_bq16_pro_77f8_download_speed", name="Down"),
        tile("sensor.zenwifi_bq16_pro_77f8_upload_speed", name="Up"),
        tile("sensor.zenwifi_bq16_pro_77f8_external_ip", name="External IP"),
    ],
}

printer = {
    "type": "grid",
    "cards": [
        heading("Printer", "mdi:printer"),
        tile("sensor.mfc_j6960dw_status", name="Status"),
        # Gauges rather than tiles: ink level is a "how full" question, and the
        # severity bands make a low cartridge legible without reading the number.
        {"type": "gauge", "entity": "sensor.mfc_j6960dw_black_toner_remaining", "name": "Black",
         "min": 0, "max": 100, "severity": {"green": 40, "yellow": 20, "red": 0}},
        {"type": "gauge", "entity": "sensor.mfc_j6960dw_cyan_toner_remaining", "name": "Cyan",
         "min": 0, "max": 100, "severity": {"green": 40, "yellow": 20, "red": 0}},
        {"type": "gauge", "entity": "sensor.mfc_j6960dw_magenta_toner_remaining", "name": "Magenta",
         "min": 0, "max": 100, "severity": {"green": 40, "yellow": 20, "red": 0}},
        {"type": "gauge", "entity": "sensor.mfc_j6960dw_yellow_toner_remaining", "name": "Yellow",
         "min": 0, "max": 100, "severity": {"green": 40, "yellow": 20, "red": 0}},
        tile("sensor.mfc_j6960dw_page_counter", name="Pages printed"),
    ],
}

media = {
    "type": "grid",
    "cards": [
        heading("Media", "mdi:television"),
        tile("media_player.playstation_5", name="PlayStation 5"),
        tile("sensor.shdwcld_online_status", name="PSN status"),
        {
            "type": "conditional",
            "conditions": [{"condition": "state", "entity": "sensor.shdwcld_now_playing", "state_not": "unknown"}],
            "card": tile("sensor.shdwcld_now_playing", name="Now playing"),
        },
        # The TV reports `unavailable` when powered off, which renders as a dead
        # tile. Hide it rather than show a permanently greyed-out card.
        {
            "type": "conditional",
            "conditions": [{"condition": "state", "entity": "media_player.lg_webos_tv_05ad", "state_not": "unavailable"}],
            "card": tile("media_player.lg_webos_tv_05ad", name="Living room TV"),
        },
    ],
}

system = {
    "type": "grid",
    "cards": [
        heading("System", "mdi:server"),
        tile("sensor.backup_last_successful_automatic_backup", name="Last backup"),
        tile("sensor.backup_next_scheduled_automatic_backup", name="Next backup"),
        # Only surfaces when an update is actually pending — an always-visible
        # row of "up to date" entries trains you to ignore the section.
        {
            "type": "conditional",
            "conditions": [{"condition": "state", "entity": "update.home_assistant_core_update", "state": "on"}],
            "card": tile("update.home_assistant_core_update", name="Core update"),
        },
        {
            "type": "conditional",
            "conditions": [{"condition": "state", "entity": "update.home_assistant_operating_system_update", "state": "on"}],
            "card": tile("update.home_assistant_operating_system_update", name="OS update"),
        },
        {
            "type": "conditional",
            "conditions": [{"condition": "state", "entity": "update.home_assistant_supervisor_update", "state": "on"}],
            "card": tile("update.home_assistant_supervisor_update", name="Supervisor update"),
        },
    ],
}

config = {
    "views": [
        {
            "type": "sections",
            "title": "Home",
            "path": "home",
            "icon": "mdi:home",
            "max_columns": 3,
            "badges": [
                {"type": "entity", "entity": "person.jeremy_corbello"},
                {"type": "entity", "entity": "weather.forecast_home"},
                {"type": "entity", "entity": "sensor.upstairs_current_temperature", "name": "Inside"},
                {"type": "entity", "entity": "binary_sensor.zenwifi_bq16_pro_77f8_wan_status", "name": "WAN"},
            ],
            "sections": [alerts, climate, lights, people, network, printer, media, system],
        },
    ]
}

out = os.environ.get(
    "OUT", os.path.join(os.path.dirname(os.path.abspath(__file__)), "overview-dashboard.json")
)
with open(out, "w", encoding="utf-8") as fh:
    fh.write(json.dumps(config, indent=2))
print("wrote", out)
print("sections:", len(config["views"][0]["sections"]))
print("cards:", sum(len(s["cards"]) for s in config["views"][0]["sections"]))
