apiVersion: v1
kind: Service
metadata:
  name: piper
  namespace: tts
  labels:
    app: piper
    app.kubernetes.io/part-of: tts-platform
spec:
  type: NodePort
  selector:
    app: piper
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 30500
      protocol: TCP
