apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inference
resources:
  - namespace.yaml
  - rbac/resource-quota.yaml
  - rbac/limit-range.yaml
  - rbac/priority-classes.yaml
  - rbac/service-account.yaml

  - vllm/pvc.yaml
  - vllm/service.yaml
  - vllm/deployment.yaml
  - embeddings/deployment.yaml
  - embeddings/service.yaml
  - monitoring/service-monitor.yaml
