apiVersion: v1
kind: ResourceQuota
metadata:
  name: osint-quota
  namespace: osint
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"
    requests.memory: 16Gi
    limits.memory: 32Gi
    pods: "20"
    count/jobs.batch: "6"
