apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plotlens-marketing
resources:
  - infisical-secret.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
  - postiz/configmap.yaml
  - postiz/deployment.yaml
  - postiz/service.yaml
  - postiz/ingressroute.yaml
  - postiz/ingressroute-webhooks.yaml
  - servicemonitor.yaml
