apiVersion: v1
kind: ResourceQuota
metadata:
  name: inference-quota
  namespace: inference
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"
    requests.memory: 20Gi
    limits.memory: 20Gi
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
    pods: "4"
