apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres-outreach-exporter
  namespace: observability
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local
  syncConfig:
    resyncInterval: "60s"
  authentication:
    universalAuth:
      secretsScope:
        projectId: db72a923-3cd8-4636-b1ff-80845dc070ca
        envSlug: dev
        secretsPath: /
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: postgres-outreach-exporter
    secretNamespace: observability
    secretType: Opaque
    creationPolicy: Orphan
