apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: worker-resources-patch.yaml
  target:
    kind: Deployment
    name: osint-worker
images:
- name: harbor.corbello.io/osint/osint-core
  newTag: d159864
