apiVersion: v1
kind: Service
metadata:
  name: proxpi
  namespace: pypi-cache
  labels:
    app: proxpi
    app.kubernetes.io/part-of: pypi-cache
spec:
  type: ClusterIP
  selector:
    app: proxpi
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
