apiVersion: v1
kind: Service
metadata:
  name: vllm-inference
  namespace: inference
  labels:
    app: vllm
    app.kubernetes.io/part-of: inference-platform
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
