apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: arboretum-health
  labels:
    app: mariadb
    app.kubernetes.io/part-of: arboretum-health
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
