apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wordpress
  namespace: arboretum-health
  labels:
    app: wordpress
    app.kubernetes.io/part-of: arboretum-health
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`arboretum-health.corbello.io`)
      kind: Rule
      services:
        - name: wordpress
          port: 80
