apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: postiz
  namespace: plotlens-marketing
  labels:
    app: postiz
    app.kubernetes.io/part-of: postiz
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`postiz.corbello.io`)
      kind: Rule
      services:
        - name: postiz
          port: 5000
