apiVersion: v1
kind: Service
metadata:
  name: postiz
  namespace: plotlens-marketing
  labels:
    app: postiz
    app.kubernetes.io/part-of: postiz
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
    - name: api
      port: 3000
      targetPort: api
  selector:
    app: postiz
