apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-data
  namespace: osint
  labels:
    app: qdrant
    app.kubernetes.io/part-of: osint-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
