apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: twenty-secrets
  namespace: crm
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local
  syncConfig:
    resyncInterval: "60s"
  authentication:
    universalAuth:
      secretsScope:
        projectId: db72a923-3cd8-4636-b1ff-80845dc070ca
        envSlug: dev
        secretsPath: /twenty
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: twenty-secrets
    secretNamespace: crm
    secretType: Opaque
    creationPolicy: Orphan
