apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotify-data
  namespace: osint
  labels:
    app: gotify
    app.kubernetes.io/part-of: osint-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-node3
  resources:
    requests:
      storage: 1Gi
