apiVersion: v1
kind: Service
metadata:
  name: text-embeddings
  labels:
    app: text-embeddings
    app.kubernetes.io/part-of: inference-platform
spec:
  type: NodePort
  selector:
    app: text-embeddings
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30851
      protocol: TCP
