apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: osint-secrets
  namespace: osint
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local
  syncConfig:
    resyncInterval: "60s"
  authentication:
    universalAuth:
      secretsScope:
        projectId: c00e26a9-9389-4cc8-9b74-75f936dfeb81
        envSlug: prod
        secretsPath: /osint
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: osint-secrets
    secretNamespace: osint
    secretType: Opaque
    creationPolicy: Orphan
