apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: osint-secrets
  namespace: osint
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab
        envSlug: prod
        secretsPath: /osint
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
  managedSecretReference:
    secretName: osint-secrets
    secretNamespace: osint
    secretType: Opaque
    creationPolicy: Orphan
  autoReload:
    deployments:
      - name: osint-worker
      - name: osint-beat
      - name: osint-core
