apiVersion: v1
kind: Secret
metadata:
  name: osint-secrets
  namespace: osint
type: Opaque
stringData:
  redis-password: "MYR9ncHb2U7fIpBCEoZgCSvSo0muw2Bzypeg4h6jbzXt5clkfglncl27tsf5k4M3rrSQMtU+oSzgjRDNPDv8+zdZv7X8C1kN/aMG9EszObRLV1H26MKLpXnn"
  redis-url: "redis://:MYR9ncHb2U7fIpBCEoZgCSvSo0muw2Bzypeg4h6jbzXt5clkfglncl27tsf5k4M3rrSQMtU%2BoSzgjRDNPDv8%2BzdZv7X8C1kN%2FaMG9EszObRLV1H26MKLpXnn@redis:6379/0"
  celery-broker-url: "redis://:MYR9ncHb2U7fIpBCEoZgCSvSo0muw2Bzypeg4h6jbzXt5clkfglncl27tsf5k4M3rrSQMtU%2BoSzgjRDNPDv8%2BzdZv7X8C1kN%2FaMG9EszObRLV1H26MKLpXnn@redis:6379/1"
  celery-result-backend: "redis://:MYR9ncHb2U7fIpBCEoZgCSvSo0muw2Bzypeg4h6jbzXt5clkfglncl27tsf5k4M3rrSQMtU%2BoSzgjRDNPDv8%2BzdZv7X8C1kN%2FaMG9EszObRLV1H26MKLpXnn@redis:6379/2"
